spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb?createDatabaseIfNotExist=true
    username: sa
    password: root
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

h2:
  console:
    settings:
      web-allow-others: false