spring:
  datasource:
    initialization-mode: never
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: sa
    password: root

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        ddl-auto: create-drop

logging:
  level:
    org:
      springframework:
        :web: DEBUG